# Generated by Django 4.0.4 on 2022-05-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_feedback_response_master_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_telegram_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='orders.telegramid', verbose_name='Telegram ID'),
        ),
    ]
