# Generated by Django 4.0.4 on 2022-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_message_is_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='messages',
        ),
        migrations.AddField(
            model_name='request',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='request', to='orders.message', verbose_name='Переписка'),
        ),
    ]
