# Generated by Django 4.0.4 on 2022-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_request_messages_request_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='request', to='orders.message', verbose_name='Переписка'),
        ),
    ]
