# Generated by Django 4.0.4 on 2022-05-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_request_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='messages',
        ),
        migrations.AddField(
            model_name='request',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='orders.message', verbose_name='Переписка'),
        ),
    ]
