# Generated by Django 4.0.4 on 2022-05-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_request_messages_request_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='orders.message', verbose_name='Переписка'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='devices',
        ),
        migrations.AddField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='owner', to='orders.device', verbose_name='Устройства'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='feedbacks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='orders.feedback', verbose_name='Отзывы'),
        ),
    ]
