# Generated by Django 4.0.4 on 2022-05-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_message_request_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='orders.request', verbose_name='Переписка'),
        ),
    ]
