# Generated by Django 4.0.4 on 2022-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='text',
            new_name='request',
        ),
        migrations.AddField(
            model_name='support',
            name='response',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Сообщение'),
        ),
    ]
