# Generated by Django 4.0.4 on 2022-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_text_support_request_support_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='is_actual',
            new_name='processed',
        ),
        migrations.AlterField(
            model_name='support',
            name='response',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ответ'),
        ),
    ]
