# Generated by Django 4.0.4 on 2022-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_request_master_request_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='master',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requests', to='orders.master'),
        ),
    ]
